import type { CreativeBrief, InstagramCard, InstagramEnginePlan } from "@/lib/content/types";

const source = "Exercise Content Studio 자체 데모 · 외부 원문 없음";

export const demoCards: InstagramCard[] = [
  {
    slide: 1,
    headline: "걸을 때 한쪽 발만 유난히 바쁘다면?",
    body: "문제는 발 하나가 아니라\n움직임을 나누는 방식일 수 있어.",
    imageDescription: "A clean educational illustration of a person walking, with subtle arrows showing uneven load distribution between both feet, navy mint coral palette",
    source,
    categoryBadge: "WALKING / RUNNING",
    summaryText: "통증 부위와 움직임 원인을 같은 것으로 단정하지 않기",
  },
  {
    slide: 2,
    headline: "혹시 이런 적 있지?",
    body: "마사지할 때는 편한데 다시 걸으면 같은 곳이 불편해져.\n\n그럴 땐 부담이 어디서 시작돼 어디로 몰리는지 같이 봐야 해.",
    imageDescription: "Simple relatable illustration showing temporary relief after foot massage and discomfort returning during walking, clean medical editorial style",
    source,
    categoryBadge: "PAIN CHECK",
    summaryText: "반복되는 불편감은 움직임의 분배도 확인하기",
  },
  {
    slide: 3,
    headline: "몸은 부담을 나눠서 움직여",
    body: "발목, 무릎, 엉덩이가 순서대로 힘을 주고받으면 한 부위가 혼자 버틸 필요가 줄어들어.",
    imageDescription: "Minimal movement chain diagram connecting ankle knee and hip with arrows, simple labeled-free medical illustration",
    source,
    categoryBadge: "BIOMECHANICS",
    summaryText: "핵심은 한 관절의 모양보다 움직임의 연결",
  },
  {
    slide: 4,
    headline: "쉽게 말하면, 몸은 팀플레이 중이야",
    body: "한 명이 계속 야근하면 지치듯이\n한 부위가 움직임을 독차지하면 부담도 그곳에 모일 수 있어.",
    imageDescription: "Light humorous concept illustration of ankle knee and hip as a friendly teamwork relay, professional not meme-like",
    source,
    categoryBadge: "MOVEMENT",
    summaryText: "다리만 혼자 일하지 않도록 역할을 나눠보기",
  },
  {
    slide: 5,
    headline: "오늘은 세 가지만 확인해봐",
    body: "1. 양쪽 발에 체중이 비슷한가\n2. 발목이 편하게 앞으로 이동하는가\n3. 엉덩이도 함께 밀어주는가",
    imageDescription: "Three-panel simple movement checklist for balanced standing ankle progression and hip push-off, clean diagram",
    source,
    categoryBadge: "EXERCISE",
    summaryText: "정답 자세보다 편안한 분배를 천천히 관찰하기",
  },
  {
    slide: 6,
    headline: "아픈 곳만 세게 풀지는 마",
    body: "강한 자극이 항상 더 좋은 건 아니야.\n통증이 커지거나 붓기·열감이 있다면 운동보다 평가가 먼저일 수 있어.",
    imageDescription: "Comparison visual between excessive aggressive self-massage and gentle movement assessment, calm clinical illustration",
    source,
    categoryBadge: "COMMON MISTAKES",
    summaryText: "불편감이 심하면 전문가 평가가 필요할 수 있어",
  },
  {
    slide: 7,
    headline: "한 줄로 정리하면",
    body: "아픈 부위만이 아니라\n움직임 전체가 부담을 어떻게 나누는지 함께 보자.",
    imageDescription: "Simple summary visual of a connected lower-body movement chain with balanced arrows and a save icon, no text",
    source,
    categoryBadge: "오늘의 핵심",
    summaryText: "저장해두고 필요할 때 다시 봐",
  },
];

export const demoCreative: CreativeBrief = {
  templateKey: "carousel_story",
  hooks: [
    ["EMPATHY", "열심히 풀어도 걸으면 다시 불편한 적 있지?", 91],
    ["CONTRARIAN", "발이 아프다고 발만 문제인 건 아닐 수 있어", 89],
    ["CURIOSITY", "왜 한쪽 발만 유난히 바쁘게 움직일까?", 94],
    ["PAIN", "한쪽 발의 반복되는 불편감, 어디서 시작될까?", 86],
    ["MISTAKE", "아픈 곳만 계속 세게 풀기 전에 확인할 것", 84],
    ["QUESTION", "걸을 때 부담은 어떻게 나뉘고 있을까?", 88],
    ["CHECKLIST", "걷기 전 10초, 이 세 가지를 체크해봐", 90],
    ["SURPRISE", "발의 부담을 줄이는 열쇠가 엉덩이일 수도 있어", 85],
    ["MYTH", "발 통증은 발만 풀면 된다는 흔한 오해", 83],
    ["STORY", "마사지 직후엔 괜찮았는데 다시 걸으니 불편했다", 87],
  ].map(([type, text, score]) => ({
    type: type as CreativeBrief["hooks"][number]["type"], text: String(text), score: Number(score), clickbaitRisk: "LOW" as const,
    scoreBreakdown: { stopPower: 23, curiosity: 18, audienceRelevance: 18, clarity: 14, specificity: 9, brandFit: 9 },
  })),
  contentAngles: [
    ["PAIN", "통증 관점", "통증 위치와 부담의 시작점이 항상 같지는 않다는 관점"],
    ["MOVEMENT", "움직임 관점", "발목·무릎·엉덩이가 부담을 나누는 연결을 관찰하는 관점"],
    ["DAILY_LIFE", "일상 관점", "출퇴근과 오래 서 있기에서 반복되는 습관을 확인하는 관점"],
    ["BEGINNER", "입문자 관점", "정답 자세보다 불편하지 않은 범위의 움직임부터 찾는 관점"],
    ["PATIENT_EDUCATION", "환자 교육 관점", "진단을 대신하지 않으면서 스스로 관찰할 기준을 알려주는 관점"],
    ["COMMON_MISTAKE", "흔한 실수 관점", "아픈 부위만 강하게 자극하는 실수를 바로잡는 관점"],
  ].map(([type, title, description]) => ({
    type: type as CreativeBrief["contentAngles"][number]["type"], title, description,
    targetAudience: "반복되는 불편감이 있는 일반인", whyItWorks: "자기 상황과 연결해 이해하기 쉽습니다.",
    expectedHookStrength: 88, saveValue: 87, shareValue: 84, recommendedCardCount: 7,
  })),
  metaphors: ["몸은 각 관절이 바통을 나누는 릴레이 팀과 비슷해", "한 부위만 계속 야근하면 결국 피곤해져"],
  empathyLines: ["혹시 이런 적 있지?", "열심히 하는데도 왜 반복될까 싶을 때가 있어"],
  humorLines: ["지금 한쪽 다리만 야근 중일지도 몰라", "몸도 팀플레이가 꼬이면 한 명이 바빠져"],
  imageBriefs: demoCards.map((card) => ({ slide: card.slide, role: card.slide === 1 ? "hook_image" : card.slide === 7 ? "summary_visual" : card.slide === 4 ? "humorous_concept_illustration" : card.slide === 6 ? "comparison_visual" : "explanatory_diagram", description: card.imageDescription })),
  hashtags: {
    brand: ["#움직임노트", "#쉽게보는재활", "#몸읽기노트"],
    topic: ["#움직임교육", "#보행분석", "#재활운동"],
    audience: ["#운동초보", "#생활속재활"],
    search: ["#발통증", "#발목통증", "#물리치료"],
    niche: ["#움직임분석", "#보행교육"],
  },
};

export const demoInstagramEngine: InstagramEnginePlan = {
  selectedAngleType: "MOVEMENT",
  selectedHookText: "왜 한쪽 발만 유난히 바쁘게 움직일까?",
  personality: "FRIENDLY",
  targetAudience: "걸을 때 반복되는 발 불편감이 있는 운동 초보",
  cardCount: demoCards.length,
  storyboard: demoCards.map((card) => ({ cardNumber: card.slide, purpose: card.slide === 1 ? "HOOK" : card.slide === 7 ? "SOURCE_CTA" : card.slide === 6 ? "MISTAKE" : card.slide === 5 ? "APPLICATION" : "EASY_EXPLANATION", headline: card.headline, visualType: card.slide === 1 ? "COVER" : card.slide === 4 ? "HUMOR" : card.slide === 5 ? "CHECKLIST" : card.slide === 7 ? "SUMMARY" : "MOVEMENT_DIAGRAM", visualDescription: card.imageDescription, layout: "브랜드 안전 여백 안의 헤드라인과 교육형 시각 요소", emotion: "친근한 이해", transition: card.slide < demoCards.length ? "다음 카드에서 한 단계 더 확인해봐." : "저장하고 출처를 확인해봐.", imageNeeded: card.slide !== 7 })),
  caption: {
    hook: "통증이 있는 곳만 계속 풀어도 비슷한 불편감이 반복되는 경우가 있지.",
    context: "걷기는 발목, 무릎, 엉덩이가 부담을 나누는 움직임이야.",
    additionalValue: "한 부위가 계속 열심히 일하는지보다 전체 연결을 함께 관찰해봐.",
    shortExplanation: "정답 자세를 찾기보다 양쪽 체중과 발목 이동, 엉덩이의 밀어내기를 천천히 비교해볼 수 있어.",
    takeaway: "한 줄로 정리하면, 아픈 곳과 부담의 시작점은 항상 같지 않을 수 있어.",
    source,
    cta: "저장해두고 다음에 걸을 때 다시 체크해봐.",
    primaryTopic: "걷기 발 통증",
    secondaryTopics: ["발목 움직임", "보행", "재활운동"],
    audienceTerms: ["운동초보", "발이 불편한 사람"],
    fullText: "통증이 있는 곳만 계속 풀어도 비슷한 불편감이 반복되는 경우가 있지.\n\n걷기는 발목, 무릎, 엉덩이가 부담을 나누는 움직임이야. 한 부위가 계속 열심히 일하는지보다 전체 연결을 함께 관찰해봐.\n\n한 줄로 정리하면, 아픈 곳과 부담의 시작점은 항상 같지 않을 수 있어.\n\nSource: Exercise Content Studio 자체 데모 · 외부 원문 없음\n\n저장해두고 다음에 걸을 때 다시 체크해봐.",
  },
  hashtags: demoCreative.hashtags,
  cta: { type: "SAVE", text: "저장해두고 다음에 걸을 때 다시 체크해봐." },
  saveValue: "걷기 전 확인할 세 가지 체크리스트",
  shareValue: "반복되는 발 불편감에 공감하는 사람과 공유할 수 있음",
  sourceNotice: "원본 콘텐츠를 그대로 번역하거나 재게시하지 않고, 핵심 개념을 참고해 별도의 설명과 해석을 더해 재구성했습니다.",
  quality: { total: 91, scores: { hook: 94, swipe: 91, clarity: 92, save: 90, share: 86, visual: 90, textDensity: 92, brand: 95, caption: 90, source: 100 }, warnings: [], ready: true },
};
