import { ExternalLink } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { listPublishedPosts } from "@/services/instagram/publishing";

export const dynamic = "force-dynamic";
export default function PublishedPage() {
  const posts = listPublishedPosts() as Array<{ id: string; mediaId: string; outputType: "INSTAGRAM_KR" | "INSTAGRAM_EN"; permalink: string; caption: string; cardCount: number; publishedAt: string; qualityScore: number; brandScore: number; status: string; username: string; title: string; expertName: string }>;
  return <><PageHeader eyebrow="Instagram" title="Published" description="공식 API 또는 Mock workflow로 완료된 게시 기록입니다." />{posts.length ? <div className="panel overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-[#dce6e3] bg-[#f4f8f6] text-xs"><tr>{["Title", "Output", "Account", "Published", "Cards", "Quality", "Status", "Instagram"].map((label) => <th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{posts.map((post) => <tr className="border-b border-[#edf1f0]" key={post.id}><td className="px-4 py-4"><strong>{post.title}</strong><span className="block text-xs text-[#758481]">Source · {post.expertName}</span></td><td className="px-4 font-bold">{post.outputType === "INSTAGRAM_EN" ? "🇺🇸 EN" : "🇰🇷 KR"}</td><td className="px-4">@{post.username}</td><td className="px-4">{new Date(post.publishedAt).toLocaleString("ko-KR")}</td><td className="px-4">{post.cardCount}</td><td className="px-4">{post.qualityScore}</td><td className="px-4 font-bold text-[#23806f]">{post.status}</td><td className="px-4">{post.permalink ? <a className="inline-flex items-center gap-1 font-bold text-[#176b63]" href={post.permalink} target="_blank" rel="noreferrer">보기 <ExternalLink size={13} /></a> : post.mediaId}</td></tr>)}</tbody></table></div> : <EmptyState title="게시 기록이 없습니다" description="Instagram Live Editor에서 최종 확인 후 게시하면 기록이 여기에 표시됩니다." />}</>;
}
