"use client";
import { useState } from "react";
import { LockKeyhole } from "lucide-react";

export function LoginForm() {
  const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ identifier, password }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error); const next = new URLSearchParams(window.location.search).get("next"); window.location.href = next && next.startsWith("/") ? next : "/"; } catch (value) { setError(value instanceof Error ? value.message : "로그인 실패"); setBusy(false); } }
  return <form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-[#d8e4e1] bg-white p-7 shadow-[0_24px_80px_rgba(26,55,52,.12)]"><span className="grid size-12 place-items-center rounded-2xl bg-[#203A5B] text-white"><LockKeyhole size={22} /></span><p className="eyebrow mt-6">Movement Content Studio</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Private Content Studio</h1><p className="text-sm leading-6 text-[#647572]">관리자 아이디 또는 소유자 이메일로 로그인해 콘텐츠와 외부 게시 기능에 접근합니다.</p><label className="mt-6 block"><span className="field-label">아이디 또는 이메일</span><input className="field-input" type="text" autoComplete="username" value={identifier} onChange={(e) => setIdentifier(e.target.value)} required /></label><label className="mt-4 block"><span className="field-label">비밀번호</span><input className="field-input" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error ? <p className="rounded-lg bg-[#fff3f1] p-3 text-xs font-bold text-[#9c443b]">{error}</p> : null}<button className="btn-primary mt-5 w-full" disabled={busy}>{busy ? "확인 중…" : "로그인"}</button></form>;
}
